### ISSUE TITLE
Change binary name

### ISSUE THREAD

**Issue by mjovanc** [kiran-4444/rgit#20]
Hey, Marcus here from X. I just checked briefly and I saw that you named the binary `r_git`, I would suggest using just `rgit` to make it easier/faster to type. What do you think?

**Comment by kiran-4444** [comment]
yeah, that sounds great. I only used `r_git` because there's already a create on crates.io with the name `rgit`. But now I realise I don't want to change the name just for the sake of publishing it to crates.io. Will change it.
